version: '3.9'

services:

  postgres:
    container_name: dbt-tuto-postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
